name: Build Windows App

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci
        shell: pwsh

      # If your app uses Playwright, we bundle Chromium so it runs offline
      - name: Preinstall Playwright Chromium
        run: |
          $env:PLAYWRIGHT_BROWSERS_PATH = '0'
          npx playwright install chromium
        shell: pwsh

      # Build NSIS installer + Portable .exe, and DO NOT publish (avoids GH_TOKEN requirement)
      - name: Build Windows artifacts
        run: npx electron-builder --win nsis portable --publish never
        shell: pwsh

      # Upload the generated files from /dist
      - name: Upload Windows build
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: |
            dist/*.exe
            dist/*.msi
            dist/*.zip
